name: Build FMPy

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: x86_64-windows
            image: windows-2022
            arch: x86_64
    runs-on: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: python --version
    - run: python -m pip install attrs dask jinja2 lark lxml matplotlib notebook numpy plotly pyqt5 pyqtgraph requests scipy
#    - run: python -m pip install attrs Jinja2 lark lxml msgpack numpy pywin32 dask[bag] requests matplotlib scipy PyQt5 pyqtgraph PyQtWebEngine kaleido notebook plotly dash-bootstrap-components
    - run: python build_cvode.py
    - run: python build_binaries.py
    - run: python build_remoting.py
    - run: python setup.py bdist_wheel
